import type { SourceOpportunity } from '../../../../src/operator/sourceHunt.ts';

// Official Tel Aviv opportunities validated during the controlled 2026-08-21
// source hunt. This is a research catalog, not a provider configuration: the
// scheduled operator may refresh/rank it and request approval, but cannot
// integrate or enable any source.
export const TEL_AVIV_SOURCE_CATALOG: SourceOpportunity[] = [
  {id:'orna_porat',name:'Orna Porat Theater for Children and Youth',officialUrl:'https://www.porat-theater.co.il/',contentType:"children's theater performances",estimatedWeeklyNetNew:12,overlapPercent:25,structure:'structured_html',official:true,freshness:1,familyRelevance:1,operationalRisk:.8,notes:'Nationwide touring dates require a strict Tel Aviv location gate.'},
  {id:'israel_philharmonic_kids',name:'Israel Philharmonic for Children',officialUrl:'https://www.ipo.co.il/ילדים/',contentType:'family concerts and musical story time',estimatedWeeklyNetNew:3,overlapPercent:20,structure:'structured_html',official:true,freshness:.9,familyRelevance:1,operationalRisk:.7,notes:'Seasonal, high-quality official content.'},
  {id:'steinhardt_family',name:'Steinhardt Museum of Natural History — Families',officialUrl:'https://smnh.tau.ac.il/events-category/for-families/',contentType:'science museum family activities',estimatedWeeklyNetNew:5,overlapPercent:20,structure:'structured_html',official:true,freshness:.9,familyRelevance:1,operationalRisk:.75,notes:'Dedicated family category and age-specific programming.'},
  {id:'tel_aviv_museum_family',name:'Tel Aviv Museum of Art — Families',officialUrl:'https://www.tamuseum.org.il/he/exhibitions-and-events/family/',contentType:'museum workshops, tours and family films',estimatedWeeklyNetNew:9,overlapPercent:30,structure:'structured_html',official:true,freshness:1,familyRelevance:1,operationalRisk:.8,notes:'Occurrence-level DigiTel overlap must be measured.'},
  {id:'israeli_opera_children',name:"Israeli Opera — Children's Opera",officialUrl:'https://www.israel-opera.co.il/en/series/childrens-opera/',contentType:"children's opera and family programs",estimatedWeeklyNetNew:3,overlapPercent:25,structure:'structured_html',official:true,freshness:.9,familyRelevance:1,operationalRisk:.75,notes:'Low cadence but high value.'},
  {id:'anu_events',name:'ANU Museum of the Jewish People — Events',officialUrl:'https://anumuseum.org.il/events/',contentType:'museum activities for families and youth',estimatedWeeklyNetNew:4,overlapPercent:20,structure:'structured_html',official:true,freshness:.9,familyRelevance:.85,operationalRisk:.8,notes:'Mixed calendar requires strict family relevance.'},
  {id:'cameri_children',name:"Cameri Theatre — Children's Shows",officialUrl:'https://www.cameri.co.il/show-category/הצגות-ילדים/',contentType:"children's theater",estimatedWeeklyNetNew:5,overlapPercent:35,structure:'structured_html',official:true,freshness:1,familyRelevance:.9,operationalRisk:.9,notes:'Taxonomy must exclude academy content.'},
  {id:'muza',name:'MUZA, Eretz Israel Museum',officialUrl:'https://www.eretzmuseum.org.il/en/',contentType:'museum workshops, planetarium and family events',estimatedWeeklyNetNew:4,overlapPercent:30,structure:'structured_html',official:true,freshness:.8,familyRelevance:.85,operationalRisk:.85,notes:'Events are distributed across museum pages.'},
  {id:'suzanne_dellal_family',name:'Suzanne Dellal — Family and Kids Programming',officialUrl:'https://suzannedellal.org.il/',contentType:'family dance, workshops and seasonal festival',estimatedWeeklyNetNew:3,overlapPercent:45,structure:'structured_html',official:true,freshness:.85,familyRelevance:.9,operationalRisk:.9,notes:'Seasonal and partially mirrored by DigiTel.'},
  {id:'bialik_museum',name:'Bialik House — Activities',officialUrl:'https://www.bialikmuseum.org.il/events/EventsPage?catId=4',contentType:'story time, family tours and workshops',estimatedWeeklyNetNew:2,overlapPercent:40,structure:'structured_html',official:true,freshness:.65,familyRelevance:.85,operationalRisk:1,notes:'Lower freshness and municipal overlap.'},
];
