import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createPlaceSlug, dryRunPlaceImport, exportPlacesCsv, exportPlacesJson, isValidCurationImageUrl, normalizePlaceName, parsePlacesCsv, validatePlaceImportRow, type PlaceImportRow } from '@/internal/placesImport';

const valid: PlaceImportRow = {
  name: 'Fixture Park', category: 'park', latitude: 32.08, longitude: 34.78,
  formatted_address: null, neighborhood: 'Test Area', short_description: null,
  is_indoor: null, is_outdoor: true, is_free: true, price_note: null,
  min_age_months: null, max_age_months: null, stroller_friendly: null,
  changing_table: null, toilets: null, shade: null, water_fountain: null, accessible: null,
  website_url: null, source_name: 'Test source', source_url: null,
  verification_status: 'verified', last_verified_at: '2026-08-05T00:00:00Z',
};

test('strict contract accepts null unknowns and never accepts family_cafe', () => { assert.deepEqual(validatePlaceImportRow(valid).errors, []); assert.match(validatePlaceImportRow({ ...valid, category: 'family_cafe' }).errors.join(','), /category/); });
test('missing contract fields and coordinates are reported, never discarded', () => { const partial = { name: '', category: 'park', latitude: null, longitude: 34.78 } as unknown as PlaceImportRow; const result = validatePlaceImportRow(partial); assert.ok(result.errors.length > 10); assert.ok(result.missingCriticalFields.includes('name')); assert.ok(result.missingCriticalFields.includes('latitude')); });
test('dry run prints PASS, FAIL and REVIEW-equivalent row status plus totals', () => { const result = dryRunPlaceImport([valid, { ...valid, name: '' }, { ...valid }]); assert.equal(result.dryRun, true); assert.deepEqual(result.rows.map((row) => row.status), ['PASS','FAIL','REVIEW']); assert.deepEqual(result.summary, { total:3, passed:1, failed:1, review:1, inserts:1, updates:0, duplicates:1 }); assert.deepEqual(result.categoryTotals, { park:2 }); assert.deepEqual(result.neighborhoodTotals, { 'Test Area':2 }); });
test('exact source + external ID safely plans an update', () => { const result = dryRunPlaceImport([{ ...valid, external_id:'official-1' }], [{ id:'db-1',name:'Old name',slug:'old-name',latitude:1,longitude:1,sourceName:'Test source',externalId:'official-1',provider:null,providerPlaceId:null }]); assert.equal(result.duplicates[0].kind, 'exact_source_id'); assert.deepEqual(result.upserts.map((item) => [item.operation,item.targetId]), [['update','db-1']]); });
test('exact provider ID safely plans an update', () => { const result = dryRunPlaceImport([{ ...valid, provider:'apple_maps',provider_place_id:'abc' }], [{ id:'db-2',name:'Existing',latitude:1,longitude:1,provider:'apple_maps',providerPlaceId:'abc' }]); assert.equal(result.duplicates[0].kind, 'exact_provider_id'); assert.equal(result.summary.updates, 1); });
test('normalized nearby names and slug collisions require review', () => { const existing = [{ id:'db-1',name:'Gan HáYeladim',slug:'gan-hayeladim',latitude:32.0801,longitude:34.7801,provider:null,providerPlaceId:null }]; const nearby = dryRunPlaceImport([{ ...valid,name:'Gan Hayeladim' }], existing); assert.equal(nearby.rows[0].status, 'REVIEW'); assert.equal(nearby.duplicates[0].kind, 'normalized_name_nearby'); const slug = dryRunPlaceImport([{ ...valid,name:'Different Name',slug:'gan-hayeladim',latitude:32.5,longitude:34.9 }], existing); assert.equal(slug.duplicates[0].kind, 'slug_collision'); });
test('uncertain coordinate matches are returned for manual review', () => { const result = dryRunPlaceImport([valid], [{ id:'db-3',name:'Different Place',latitude:32.08005,longitude:34.78005,provider:null,providerPlaceId:null }]); assert.equal(result.rows[0].status, 'REVIEW'); assert.match(result.manualReview[0].reason, /different name/); assert.equal(result.upserts.length, 0); });
test('name and slug normalization are deterministic for English and Hebrew', () => { assert.equal(normalizePlaceName('  Gán—Park '), 'gan park'); assert.equal(createPlaceSlug('Family Park'), 'family-park'); assert.match(createPlaceSlug('גן ילדים'), /^place-/); });
test('CSV parser supports quoted addresses and null empty cells', () => { const header = Object.keys(valid).join(','); const values = Object.values({ ...valid, name:'Fixture, Park',formatted_address:'10 Test St, Tel Aviv' }).map((value) => value == null ? '' : String(value)); values[0] = '"Fixture, Park"'; values[4] = '"10 Test St, Tel Aviv"'; const rows = parsePlacesCsv(`${header}\n${values.join(',')}`); assert.equal(rows[0].name, 'Fixture, Park'); assert.equal(rows[0].formatted_address, '10 Test St, Tel Aviv'); assert.equal(rows[0].is_indoor, null); });
test('URL validation permits secure URLs without fetching', () => { assert.equal(isValidCurationImageUrl('https://cdn.example.test/image?id=1'), true); assert.equal(isValidCurationImageUrl('http://example.test/a.jpg'), false); assert.match(validatePlaceImportRow({ ...valid, source_url:'file:///secret' }).errors.join(','), /source_url/); });
test('CSV and JSON exports preserve reviewable curation data', () => { const rows = [{ ...valid, partner_tags:['weekend','partner'] }]; assert.match(exportPlacesCsv(rows), /weekend\|partner/); assert.deepEqual(JSON.parse(exportPlacesJson(rows))[0].partner_tags, ['weekend','partner']); });
test('published JSON schema has the exact category scope and required contract', () => { const schema = JSON.parse(readFileSync(new URL('../../docs/places/tel-aviv-places.schema.json', import.meta.url), 'utf8')); assert.equal(schema.items.properties.category.enum.length, 12); assert.equal(schema.items.properties.category.enum.includes('family_cafe'), false); assert.ok(schema.items.required.includes('last_verified_at')); });
