import test from 'node:test';
import assert from 'node:assert/strict';
import { runScheduledOperator, type ScheduledCycleReport, type ScheduledOperatorStore, type ScheduledRunContext } from './scheduledRunner.ts';
import { contentHealth } from './scoring.ts';
import type { ContentCandidate, ProviderSnapshot } from './types.ts';
import type { OwnerApprovalRequest } from './approval.ts';

const now=new Date('2030-01-01T08:00:00Z');
const context={runId:'run',taskId:'task'};
const content:ContentCandidate={id:'event',cityId:'tel_aviv',provider:'tel_aviv_digitel',title:'אירוע בוטל למבוגרים 18+',description:null,startsAt:'2030-01-02T10:00:00Z',endsAt:null,category:'community',ageMinMonths:null,ageMaxMonths:null,priceNote:null,latitude:32.08,longitude:34.78,sourceUrl:'https://example.com',registrationUrl:null,eventStatus:'scheduled',occurrenceFingerprint:'fingerprint'};
const provider:ProviderSnapshot={key:'tel_aviv_digitel',cityId:'tel_aviv',enabled:true,scheduleCron:'17 */6 * * *',cronActive:true,cronMatches:1,runs:[{provider:'tel_aviv_digitel',status:'success',sourceComplete:true,fetched:100,normalized:10,duplicates:0,invalidOrErrors:0,archived:0,startedAt:'2030-01-01T07:00:00Z',completedAt:'2030-01-01T07:01:00Z'}]};

function mockStore(overrides:Partial<ScheduledOperatorStore>={}){const approvals:Array<{request:OwnerApprovalRequest;key:string}>=[],completed:ScheduledCycleReport[]=[],failed:string[]=[];const store:ScheduledOperatorStore={beginRun:async()=>context,loadContent:async()=>[content],loadProviders:async()=>[provider],loadLatestProductHealth:async()=>contentHealth({sourceCompleteness:1,freshness:1,validity:1,uniqueness:1,familyRelevance:1,ageCoverage:1,priceCoverage:1,locationCoverage:1,registrationCoverage:1,categoryConfidence:1}),checkUrls:async()=>new Set(),loadPendingApprovalKeys:async()=>new Set(),createApproval:async(request,key)=>{approvals.push({request,key});},completeRun:async(_context,report)=>{completed.push(report);},failRun:async(_context,error)=>{failed.push(error);},...overrides};return{store,approvals,completed,failed};}

test('Daily scheduled cycle audits content, persists a report and creates only pending Yellow requests',async()=>{const state=mockStore();const report=await runScheduledOperator('daily',state.store,{now,idFactory:(()=>{let i=0;return()=>`approval-${++i}`;})()});assert.equal(report.mode,'daily');assert.equal(state.completed.length,1);assert.equal(state.approvals.length,2);assert.ok(state.approvals.every(({request})=>request.status==='PENDING'));assert.ok(state.approvals.every(({request})=>request.dryRunResults&&request.category==='production_content_correction'));assert.equal(report.autonomousFixes.length,0);assert.match(report.ownerReport,/Waiting for approval/);});
test('Daily URL probing contributes a broken-link finding without changing content',async()=>{const state=mockStore({checkUrls:async()=>new Set(['https://example.com'])});const report=await runScheduledOperator('daily',state.store,{now,idFactory:()=>crypto.randomUUID()});assert.ok(report.findings.some((finding)=>finding.id==='content:broken-url'));});
test('pending operator keys suppress duplicate approval requests',async()=>{const state=mockStore({loadPendingApprovalKeys:async()=>new Set(['content_quality:content:cancellation-mismatch','content_quality:content:adult-only'])});const report=await runScheduledOperator('daily',state.store,{now,idFactory:()=> 'unused'});assert.equal(report.approvalsCreated.length,0);});
test('Weekly Source Hunt ranks candidates but creates at most three proposals and performs no integration',async()=>{const state=mockStore();const catalog=Array.from({length:5},(_,index)=>({id:`source-${index}`,name:`Source ${index}`,officialUrl:`https://official${index}.example`,contentType:'family events',estimatedWeeklyNetNew:20-index,overlapPercent:10,structure:'api' as const,official:true,freshness:1,familyRelevance:1,operationalRisk:1,notes:''}));const report=await runScheduledOperator('source_hunt',state.store,{now,sourceCatalog:catalog,idFactory:(()=>{let i=0;return()=>`source-approval-${++i}`;})()});assert.equal(report.opportunities.length,5);assert.equal(report.approvalsCreated.length,3);assert.ok(state.approvals.every(({request})=>request.recommendedAction.includes('dry run')));assert.ok(state.approvals.every(({request})=>(request.dryRunResults as {productionWrites:number}).productionWrites===0));});
test('scheduled failure is isolated, audited and never reported completed',async()=>{const state=mockStore({loadContent:async()=>{throw new Error('provider observation failed')}});await assert.rejects(()=>runScheduledOperator('daily',state.store,{now}),/provider observation failed/);assert.deepEqual(state.failed,['provider observation failed']);assert.equal(state.completed.length,0);});
test('unattended runner rejects Yellow execution modes before creating a run',async()=>{const state=mockStore();await assert.rejects(()=>runScheduledOperator('city_expansion',state.store,{now}));assert.equal(state.completed.length,0);});
